import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser, SECURITY_KEHADIRAN_ACCESS } from "@/lib/auth";
import ScrollRight from "@/components/ScrollRight";
import SubmitButton from "@/components/SubmitButton";
import { generateNextMonth } from "./actions";
import type { SecurityGuard, SecurityShift, ShiftType } from "@/lib/types";
import { MONTH_NAMES, SHIFT_LABELS, SHIFT_HOURS } from "@/lib/types";

// Only September 2026 is seeded so far (from the source spreadsheet) —
// swap this back to a free year input once other years exist, same as
// YEAR in report/page.tsx.
const YEAR = 2026;

const SHIFT_BADGE: Record<ShiftType, string> = {
  pagi: "bg-amber-50 text-amber-700",
  malam: "bg-indigo-50 text-indigo-700",
  off: "text-gray-300",
};

export default async function SecurityPage({
  searchParams,
}: {
  searchParams: Promise<{ month?: string; error?: string }>;
}) {
  const user = await getCurrentUser();
  if (user?.role !== "pengurus") redirect("/report");

  const sp = await searchParams;
  const { error } = sp;
  const now = new Date();
  const month =
    Number(sp.month) || (now.getFullYear() === YEAR ? now.getMonth() + 1 : 9);

  const daysInMonth = new Date(YEAR, month, 0).getDate();
  const monthStr = String(month).padStart(2, "0");
  const rangeStart = `${YEAR}-${monthStr}-01`;
  const rangeEnd = `${YEAR}-${monthStr}-${String(daysInMonth).padStart(2, "0")}`;

  const supabase = await createClient();
  const [{ data: guards }, { data: shifts }, { data: checkins }, { data: patrols }] =
    await Promise.all([
      supabase
        .from("security_guards")
        .select("*")
        .eq("is_active", true)
        .order("created_at")
        .returns<SecurityGuard[]>(),
      supabase
        .from("security_shifts")
        .select("*")
        .gte("shift_date", rangeStart)
        .lte("shift_date", rangeEnd)
        .returns<SecurityShift[]>(),
      supabase
        .from("security_checkins")
        .select("guard_id, status")
        .gte("shift_date", rangeStart)
        .lte("shift_date", rangeEnd)
        .returns<{ guard_id: string; status: "pending" | "confirmed" | "rejected" }[]>(),
      supabase
        .from("security_patrols")
        .select("guard_id")
        .gte("shift_date", rangeStart)
        .lte("shift_date", rangeEnd)
        .returns<{ guard_id: string }[]>(),
    ]);

  const shiftMap = new Map<string, ShiftType>();
  const autoGenerated = new Set<string>();
  (shifts ?? []).forEach((s) => {
    const key = `${s.guard_id}-${s.shift_date}`;
    shiftMap.set(key, s.shift_type);
    if (s.note?.startsWith("Auto-generated")) autoGenerated.add(key);
  });

  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(
    now.getDate()
  ).padStart(2, "0")}`;

  const days = Array.from({ length: daysInMonth }, (_, i) => {
    const date = new Date(YEAR, month - 1, i + 1);
    const dateStr = `${YEAR}-${monthStr}-${String(i + 1).padStart(2, "0")}`;
    return {
      date,
      dateStr,
      dayName: date.toLocaleDateString("id-ID", { weekday: "short" }),
      isPast: dateStr < todayStr,
      isToday: dateStr === todayStr,
    };
  });

  const rows = (guards ?? []).map((g) => {
    const cells = days.map((d) => {
      const key = `${g.id}-${d.dateStr}`;
      const type = shiftMap.get(key) ?? null;
      return { type, auto: autoGenerated.has(key), isPast: d.isPast, isToday: d.isToday };
    });
    const totals = cells.reduce(
      (acc, c) => {
        if (c.type) acc[c.type] += 1;
        return acc;
      },
      { pagi: 0, malam: 0, off: 0 } as Record<ShiftType, number>
    );
    const totalJam = totals.pagi * SHIFT_HOURS.pagi + totals.malam * SHIFT_HOURS.malam;
    return { guard: g, cells, totals, totalJam };
  });

  // Kehadiran & Patroli summary, per guard, for the same month as the
  // schedule above — this is the raw material for deciding bonus/
  // insentif (attendance rate vs. scheduled shifts, plus how many patrol
  // reports came in), not a bonus calculation itself: pengurus reads
  // this and decides, nothing here computes a payout figure.
  const checkinCounts = new Map<
    string,
    { pending: number; confirmed: number; rejected: number }
  >();
  (checkins ?? []).forEach((c) => {
    const entry = checkinCounts.get(c.guard_id) ?? {
      pending: 0,
      confirmed: 0,
      rejected: 0,
    };
    entry[c.status]++;
    checkinCounts.set(c.guard_id, entry);
  });

  const patrolCounts = new Map<string, number>();
  (patrols ?? []).forEach((p) => {
    patrolCounts.set(p.guard_id, (patrolCounts.get(p.guard_id) ?? 0) + 1);
  });

  const summaryRows = rows.map(({ guard, totals }) => {
    const scheduledShifts = totals.pagi + totals.malam;
    const counts = checkinCounts.get(guard.id) ?? {
      pending: 0,
      confirmed: 0,
      rejected: 0,
    };
    const attendanceRate =
      scheduledShifts > 0 ? Math.round((counts.confirmed / scheduledShifts) * 100) : null;
    return {
      guard,
      scheduledShifts,
      ...counts,
      attendanceRate,
      patrolCount: patrolCounts.get(guard.id) ?? 0,
    };
  });

  const periodLabel = `${MONTH_NAMES[month - 1]} ${YEAR}`;

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="flex flex-wrap items-center justify-between gap-4 mb-4">
        <div>
          <h1 className="text-lg font-semibold text-gray-900">
            Jadwal Security {periodLabel}
          </h1>
          <p className="text-xs text-gray-400 mt-1">
            Pagi 07.00–19.00 · Malam 19.00–07.00 · OFF: tidak bertugas
            {SECURITY_KEHADIRAN_ACCESS.includes(user.email) && (
              <>
                {" · "}
                <a
                  href="/security/kehadiran"
                  className="text-blue-600 hover:underline"
                >
                  Kehadiran &amp; Patroli
                </a>
              </>
            )}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <form action={generateNextMonth}>
            <SubmitButton
              pendingText="Membuat..."
              className="text-sm rounded border border-gray-300 px-3 py-1.5 hover:bg-gray-50 transition"
            >
              Generate Bulan Berikutnya
            </SubmitButton>
          </form>
          <form className="flex gap-2 items-center text-sm" action="/security">
            <select
              name="month"
              defaultValue={month}
              className="rounded border border-gray-300 px-2 py-1"
            >
              {MONTH_NAMES.map((m, i) => (
                <option key={m} value={i + 1}>
                  {m}
                </option>
              ))}
            </select>
            <span className="rounded border border-gray-200 bg-gray-50 px-2 py-1 text-gray-500 w-20 text-center">
              {YEAR}
            </span>
            <button
              type="submit"
              className="rounded border border-gray-300 px-3 py-1 hover:bg-gray-50"
            >
              Lihat
            </button>
          </form>
        </div>
      </div>

      {error && (
        <div className="mb-4 text-sm text-red-700 bg-red-50 border border-red-200 rounded px-3 py-2">
          {error}
        </div>
      )}

      <ScrollRight className="bg-white border border-gray-200 rounded-lg overflow-x-auto">
        <table className="w-full text-xs">
          <thead className="bg-gray-50 text-gray-500 text-left">
            <tr>
              <th className="px-3 py-2 font-medium sticky left-0 bg-gray-50 whitespace-nowrap">
                Nama
              </th>
              {days.map((d) => (
                <th
                  key={d.dateStr}
                  className={`px-2 py-2 font-medium text-center whitespace-nowrap ${
                    d.isToday
                      ? "bg-blue-50 text-blue-700"
                      : d.isPast
                        ? "bg-gray-100 text-gray-400"
                        : ""
                  }`}
                >
                  {d.dayName}
                  <div className="text-gray-400 font-normal">
                    {d.date.getDate()}
                  </div>
                </th>
              ))}
              <th className="px-2 py-2 font-medium text-center whitespace-nowrap">
                Pagi
              </th>
              <th className="px-2 py-2 font-medium text-center whitespace-nowrap">
                Malam
              </th>
              <th className="px-2 py-2 font-medium text-center whitespace-nowrap">
                OFF
              </th>
              <th className="px-2 py-2 font-medium text-center whitespace-nowrap">
                Jam
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {rows.map(({ guard, cells, totals, totalJam }) => (
              <tr key={guard.id}>
                <td className="px-3 py-2 whitespace-nowrap sticky left-0 bg-white font-medium text-gray-900">
                  {guard.name}
                </td>
                {cells.map((c, i) => (
                  <td
                    key={i}
                    className={`px-2 py-2 text-center whitespace-nowrap ${
                      c.isToday ? "bg-blue-50" : c.isPast ? "bg-gray-50" : ""
                    }`}
                  >
                    <span
                      title={c.auto ? "Digenerate otomatis dari pola rotasi" : undefined}
                      className={`rounded px-1.5 py-0.5 ${
                        c.type ? SHIFT_BADGE[c.type] : "text-gray-200"
                      } ${c.auto ? "ring-1 ring-dashed ring-gray-300" : ""}`}
                    >
                      {c.type ? SHIFT_LABELS[c.type] : "·"}
                      {c.auto && "*"}
                    </span>
                  </td>
                ))}
                <td className="px-2 py-2 text-center text-gray-500">
                  {totals.pagi}
                </td>
                <td className="px-2 py-2 text-center text-gray-500">
                  {totals.malam}
                </td>
                <td className="px-2 py-2 text-center text-gray-500">
                  {totals.off}
                </td>
                <td className="px-2 py-2 text-center text-gray-500 whitespace-nowrap">
                  {totalJam} Jam
                </td>
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td
                  colSpan={days.length + 5}
                  className="px-3 py-6 text-center text-gray-400"
                >
                  Belum ada data jadwal.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </ScrollRight>
      {rows.some((r) => r.cells.some((c) => c.auto)) && (
        <p className="text-xs text-gray-400 mt-2">
          * Digenerate otomatis dari pola rotasi — belum tentu final, cek
          ulang sebelum dipakai.
        </p>
      )}

      {SECURITY_KEHADIRAN_ACCESS.includes(user.email) && (
      <div className="mt-8">
        <h2 className="text-sm font-medium text-gray-700 mb-1">
          Ringkasan Kehadiran &amp; Patroli {periodLabel}
        </h2>
        <p className="text-xs text-gray-400 mb-3">
          Bahan pertimbangan bonus/insentif — bukan perhitungan otomatis.
          Detail per absen ada di{" "}
          <a href="/security/kehadiran" className="text-blue-600 hover:underline">
            Kehadiran &amp; Patroli
          </a>
          .
        </p>
        <div className="bg-white border border-gray-200 rounded-lg overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 text-gray-500 text-left">
              <tr>
                <th className="px-3 py-2 font-medium">Nama</th>
                <th className="px-3 py-2 font-medium text-center">
                  Shift Terjadwal
                </th>
                <th className="px-3 py-2 font-medium text-center">
                  Absen Dikonfirmasi
                </th>
                <th className="px-3 py-2 font-medium text-center">Menunggu</th>
                <th className="px-3 py-2 font-medium text-center">Ditolak</th>
                <th className="px-3 py-2 font-medium text-center">
                  Tingkat Kehadiran
                </th>
                <th className="px-3 py-2 font-medium text-center">
                  Laporan Patroli
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {summaryRows.map((s) => (
                <tr key={s.guard.id}>
                  <td className="px-3 py-2 font-medium text-gray-900 whitespace-nowrap">
                    {s.guard.name}
                  </td>
                  <td className="px-3 py-2 text-center text-gray-500">
                    {s.scheduledShifts}
                  </td>
                  <td className="px-3 py-2 text-center text-emerald-700">
                    {s.confirmed}
                  </td>
                  <td className="px-3 py-2 text-center text-gray-500">
                    {s.pending}
                  </td>
                  <td className="px-3 py-2 text-center text-red-600">
                    {s.rejected}
                  </td>
                  <td className="px-3 py-2 text-center">
                    {s.attendanceRate === null ? (
                      <span className="text-gray-300">—</span>
                    ) : (
                      <span
                        className={
                          s.attendanceRate >= 90
                            ? "text-emerald-700 font-medium"
                            : s.attendanceRate >= 70
                              ? "text-amber-600 font-medium"
                              : "text-red-600 font-medium"
                        }
                      >
                        {s.attendanceRate}%
                      </span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-center text-gray-500">
                    {s.patrolCount}
                  </td>
                </tr>
              ))}
              {summaryRows.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-3 py-6 text-center text-gray-400">
                    Belum ada data.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
      )}
    </div>
  );
}
